### ISSUE TITLE
the implement of TD error in Actor_Critic

### ISSUE THREAD

**Issue by mxlin043** [Skylark0924/Machine-Learning-Basic-Codes#1]
https://github.com/Skylark0924/Machine-Learning-is-ALL-You-Need/blob/766a50ba07c21f6e9f6c8c48a819f6e075e97b78/RL_Actor_Critic/17Actor_Critic.py#L80-L92

Shouldn't  **_R_** here be set as the value estimation of the last state? 
If I understand correctly, if _**R**_ is set to 0, the returns for the later _**t**_ become less accurate, and it also fails to reflect the temporal difference.

**Comment by Skylark0924** [comment]
Hi, I have released my new RL Python package. Please check this new implementation of actor-critic.

<img width="866" alt="image-20230825121432059" src="https://github.com/Skylark0924/Machine-Learning-is-ALL-You-Need/assets/24936522/8c8cd8d5-6bae-470d-9fd5-45d24b29f53b">


[![Release](https://img.shields.io/github/v/release/Skylark0924/Rofunc)](https://pypi.org/project/rofunc/)
![License](https://img.shields.io/github/license/Skylark0924/Rofunc?color=blue)
![](https://img.shields.io/github/downloads/skylark0924/Rofunc/total)
[![](https://img.shields.io/github/issues-closed-raw/Skylark0924/Rofunc?color=brightgreen)](https://github.com/Skylark0924/Rofunc/issues?q=is%3Aissue+is%3Aclosed)
[![](https://img.shields.io/github/issues-raw/Skylark0924/Rofunc?color=orange)](https://github.com/Skylark0924/Rofunc/issues?q=is%3Aopen+is%3Aissue)
[![Documentation Status](https://readthedocs.org/projects/rofunc/badge/?version=latest)](https://rofunc.readthedocs.io/en/latest/?badge=latest)
[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2FSkylark0924%2FRofunc%2Fbadge%3Fref%3Dmain&style=flat)](https://actions-badge.atrox.dev/Skylark0924/Rofunc/goto?ref=main)

> **Repository address: https://github.com/Skylark0924/Rofunc**
